[package]
name = "my-rust-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
swift-bridge-build = "0.1"
swift-bridge-cli = "0.1"

[dependencies]
swift-bridge = "0.1"